vk.addListener.messages(function(msg) {
    if(msg.body == "Где ты живешь?")msg.send("Далекоооо...");
    if(msg.body == "Где ты живешь")msg.send("Далекоооо...");
    if(msg.body == "где ты живешь?")msg.send("Далекоооо...");
    if(msg.body == "где ты живешь?")msg.send("Далекоооо...");
    if(msg.body == "Во что играешь?")msg.send("В твою маму))00))");
    if(msg.body == "Во что играешь")msg.send("В твою маму))00)");
    if(msg.body == "во что играешь?")msg.send("В твою маму))00)");
    if(msg.body == "во что играешь")msg.send("В твою маму))00)");
    if(msg.body == "Чем занимаешся?")msg.send("С тобой общяюсь");
    if(msg.body == "Чем занимаешся")msg.send("С тобой общяюсь");
    if(msg.body == "чем занимаешся?")msg.send("С тобой общяюсь");
    if(msg.body == "чем занимаешся")msg.send("С тобой общяюсь");
    if(msg.body == "Играеш?")msg.send("Нет, с тобой общяюсь");
    if(msg.body == "играешь?")msg.send("Нет, с тобой общяюсь");
    if(msg.body == "играешь")msg.send("Нет, с тобой общяюсь");
    if(msg.body == "Играешь")msg.send("Нет, с тобой общяюсь");
    if(msg.body == "хай")msg.send("Привет");
    if(msg.body == "Хай")msg.send("Привет");
    if(msg.body == "Приветик")msg.send("Привет");
    if(msg.body == "приветик")msg.send("Привет");
    if(msg.body == "Прив")msg.send("Привет");
    if(msg.body == "прив")msg.send("Привет");
    if(msg.body == "Как дела?")msg.send("Норм");
    if(msg.body == "как дела?")msg.send("Норм");
    if(msg.body == "Как дела")msg.send("Норм");
    if(msg.body == "как дела")msg.send("Норм");
    if(msg.body == "Что делаешь?")msg.send("А что может делать бот?");
    if(msg.body == "Что делаешь")msg.send("А что может делать бот?");
    if(msg.body == "что делаешь?")msg.send("А что может делать бот?");
    if(msg.body == "что делаешь")msg.send("А что может делать бот?");
    if(msg.body == "хз")msg.send("Добавь в друзья");
    if(msg.body == "Хз")msg.send("Добавь в друзья");
    if(msg.body == "незнаю")msg.send("Добавь в дрвзья");
    if(msg.body == "не знаю")msg.send("Добавь в друзья");
    if(msg.body == "Незнаю")msg.send("Добавь в друзья");
    if(msg.body == "Не знаю")msg.send("Добавь в друзья");
    if(msg.body == "срет")msg.send("Смешно...");
    if(msg.body == "Ты гей?")msg.send("Я бот...");
    if(msg.body == "ты гей?")msg.send("Я бот...");
    if(msg.body == "Ты гей")msg.send("Я бот...");
    if(msg.body == "ты гей")msg.send("Я бот...");
    if(msg.body == "...")msg.send(".-.");
    if(msg.body == "ок")msg.send(":)");
    if(msg.body == "нет")msg.send("Да!");
    if(msg.body == "я тебя люблю")msg.send("А я тебя НЕТ!");
    if(msg.body == "хорошо")msg.send("=)");
    if(msg.body == "Ок")msg.send(":)");
    if(msg.body == "Нет")msg.send("Да!");
    if(msg.body == "Пизда")msg.send("Без мата!");
    if(msg.body == "Елда")msg.send("Прекращай!");
    if(msg.body == "Хорошо")msg.send("=)");
    if(msg.body == "сколько сейчас время")msg.send("У меня нету часов =(");
    if(msg.body == "Сколько сейчас время")msg.send("У меня нету часов =(");
    if(msg.body == "сколько сейчас время?")msg.send("У меня нету часов =(");
    if(msg.body == "Сколько сейчас время?")msg.send("У меня нету часов =(");
    if(msg.body == "а у кого они есть?")msg.send("Проверь, может у тебя");
    if(msg.body == "а у кого они есть")msg.send("Проверь, может у тебя");
    if(msg.body == "А у кого они есть?")msg.send("Проверь, может у тебя");
    if(msg.body == "А у кого они есть")msg.send("Проверь, может у тебя");
    if(msg.body == "погода")msg.send("Какая у вас погода?");
    if(msg.body == "Погода")msg.send("Какая у вас погода?");
    if(msg.body == "Я тебя люблю")msg.send("А я тебя нет");
    if(msg.body == "давай дружить")msg.send("Давай");
    if(msg.body == "давай дружить?")msg.send("Давай");
    if(msg.body == "Давай дружить?")msg.send("Давай");
    if(msg.body == "Давай дружить")msg.send("Давай");
    if(msg.body == "Го дота, я создал")msg.send("Прости, я натурал");
    if(msg.body == "я на нуле")msg.send("А у меня сотка");
    if(msg.body == "Я на нуле")msg.send("А у меня сотка");
    if(msg.body == "займи косарь до завтра")msg.send("У меня только сотка");
    if(msg.body == "Займи косарь до завтра")msg.send("У меня только сотка");
    if(msg.body == "здохни")msg.send("Гуляй лесом");
    if(msg.body == "Здохни")msmsg.send("Гуляй лесом");
    if(msg.body == "умри")msg.send("Гуляй лесом");
    if(msg.body == "Умри")msg.send("Гуляй лесом");
    if(msg.body == "Сколько тебе лет?")msg.send("На 4 дн старше чем ты=)");
    if(msg.body == "сколько тебе лет?")msg.send("На 4 дн старше чем ты=)");
    if(msg.body == "Сколько тебе лет")msg.send("На 4 дн старше чем ты=)");
    if(msg.body == "сколько тебе лет")msg.send("На 4 дн старше чем ты=)");
    if(msg.body == "Хакер")msg.send("THack3forU");
    if(msg.body == "хакер")msg.send("THack3forU");
    if(msg.body == "Кто тебя сделал?")msg.send("Над моим созданием работали 98 людей, наверно=) я хз кто работал над о мной=)");
    if(msg.body == "кто тебя сделал?")msg.send("Над моим созданием работали 98 людей, наверно=) я хз кто работал над о мной=)");
    if(msg.body == "Ты тупой?")msg.send("Умнее чем ты!");
    if(msg.body == "Ты тупой")msg.send("Умнее чем ты!");
    if(msg.body == "ты тупой?")msg.send("Умнее чем ты!");
    if(msg.body == "ты тупой")msg.send("Умнее чем ты!");
    if(msg.body == "Тупой")msg.send("Умнее чем ты")
    if(msg.body == "тупой")msg.send("Умнее чем ты");
    if(msg.body == "Кто тебя сделал")msg.send("Над моим созданием работали 98 людей, наверно=) я хз кто работал над о мной=)");
    if(msg.body == "кто тебя сделал")msg.send("Над моим созданием работали 98 людей, наверно=) я хз кто работал над о мной=)");
    if(msg.body == "Секс")msg.send("Я не против");
    if(msg.body == "секс")msg.send("Я не против");
    if(msg.body == "Как тебя зовут?")msg.send("Бот");
    if(msg.body == "Как тебя зовут")msg.send("Бот");
    if(msg.body == "как тебя зовут")msg.send("Бот");
    if(msg.body == "как тебя зовут?")msg.send("Бот");
    if(msg.body == "А почему?")msg.send("Потому");
    if(msg.body == "а почему?")msg.send("Потому");
    if(msg.body == "а почему")msg.send("Потому");
    if(msg.body == "А почему")msg.send("Потому");
    if(msg.body == "Ты лох")msg.send("Мать твоя лох)))0)");
    if(msg.body == "Ты лох!")msg.send("Мать твоя лох)))0)");
    if(msg.body == "ты лох")msg.send("Мать твоя лох)))0)");
    if(msg.body == "ты лох!")msg.send("Мать твоя лох)))0)");
    if(msg.body == "Пока")msg.send("Ага, удачи");
    if(msg.body == "пока")msg.send("Ага, удачи");
    if(msg.body == "Прощай")msg.send("Ага, удачи");
    if(msg.body == "прощай")msg.send("Ага, удачи");
